-- addon/bmpl/encode.lua
--
-- Mirrors web/src/lib/live/codec.ts exactly: same STRIP geometry, same 12-byte header, same
-- CRC-16/CCITT-FALSE, same marker + MSB-first cell layout, same 61-byte roster chunking. Pinned by
-- addon/bmpl/tests/vectors.txt (generated by scripts/live-vectors.ts from codec.ts) and checked
-- in-game by `/bmpl selftest` in main.lua.
--
-- Pure: no WoW API calls in this file. Byte arrays are plain Lua tables, 1-indexed, values 0-255.
-- Lua 5.1 (WoW's runtime) has no bitwise operators, so CRC/shift/mask work is done with arithmetic
-- (mod / floor / powers of two) instead — see `xor16` and `bytesToBits` below.

local ADDON_NAME, ns = ...

local Encode = {}
ns.Encode = Encode

-- Same shape and values as STRIP in codec.ts.
local STRIP = {
  cols = 40,
  rows = 16,
  cell = 6,
  dataCells = 39 * 15,
  headerBytes = 12,
  payloadMax = 61,
  version = 1,
}
Encode.STRIP = STRIP

local MAGIC = { 0x62, 0x6d, 0x70, 0x6c } -- "bmpl"

-- Flat, 1-indexed cell index for the 40x16 grid: idx(x, y) with x, y 0-indexed (x: 0..39, y: 0..15).
-- Shared with strip.lua so the encoder's bit layout and the painter's texture grid always agree.
local function cellIndex(x, y)
  return y * STRIP.cols + x + 1
end
Encode.cellIndex = cellIndex

-- 16-bit XOR via bit decomposition (no bit library available to WoW addons in Lua 5.1).
local function xor16(a, b)
  local result = 0
  local place = 1
  for _ = 1, 16 do
    local abit = a % 2
    local bbit = b % 2
    if abit ~= bbit then result = result + place end
    a = (a - abit) / 2
    b = (b - bbit) / 2
    place = place * 2
  end
  return result
end

-- CRC-16/CCITT-FALSE: poly 0x1021, init 0xFFFF, no reflection, no final xor. `bytes` is a 1-indexed
-- table, `len` the number of bytes to read from it (matches crc16() in codec.ts byte for byte).
local function crc16(bytes, len)
  local crc = 0xffff
  for i = 1, len do
    crc = xor16(crc, (bytes[i] * 256) % 0x10000) -- crc ^= b << 8
    for _ = 1, 8 do
      local shifted = (crc * 2) % 0x10000
      if crc >= 0x8000 then
        crc = xor16(shifted, 0x1021)
      else
        crc = shifted
      end
    end
  end
  return crc
end
Encode.crc16 = crc16

-- `bytes`/`byteLen`: a 1-indexed table with `byteLen` bytes. MSB first; zero-padded once the buffer
-- runs out, exactly like bytesToBits() in codec.ts.
local function bytesToBits(bytes, byteLen, count)
  local bits = {}
  for i = 0, count - 1 do
    local byteIndex = math.floor(i / 8) + 1
    local byte = 0
    if byteIndex <= byteLen then byte = bytes[byteIndex] or 0 end
    local bitPos = 7 - (i % 8)
    bits[i + 1] = math.floor(byte / (2 ^ bitPos)) % 2
  end
  return bits
end

-- `frame`: { version, rosterSeq, chunkIndex, chunkCount, payload (1-indexed byte table), payloadLen }.
-- Returns the encoded byte table (1-indexed) and its length — always headerBytes + payloadLen, never
-- padded out to a fixed frame size (the bug this mirrors from Task 1: encodeFrame() in codec.ts sizes
-- the output to the real payload, and the CRC covers exactly what is sent).
function Encode.encodeFrame(frame)
  local payload = frame.payload or {}
  local payloadLen = frame.payloadLen or 0
  if payloadLen > STRIP.payloadMax then
    error(string.format("bmpl: payload of %d bytes exceeds %d", payloadLen, STRIP.payloadMax))
  end
  local out = {}
  out[1], out[2], out[3], out[4] = MAGIC[1], MAGIC[2], MAGIC[3], MAGIC[4]
  out[5] = frame.version
  out[6] = frame.rosterSeq % 256
  out[7] = math.floor(frame.rosterSeq / 256) % 256
  out[8] = frame.chunkIndex
  out[9] = frame.chunkCount
  out[10] = payloadLen

  local crcInput = {}
  for i = 1, 10 do crcInput[i] = out[i] end
  for i = 1, payloadLen do crcInput[10 + i] = payload[i] end
  local crc = crc16(crcInput, 10 + payloadLen)
  out[11] = crc % 256
  out[12] = math.floor(crc / 256) % 256

  for i = 1, payloadLen do out[STRIP.headerBytes + i] = payload[i] end
  return out, STRIP.headerBytes + payloadLen
end

-- The full 40x16 matrix (1 = white), 1-indexed via cellIndex(): marker row, marker column, then the
-- frame's bits row-major, MSB first — exactly encodeCells() in codec.ts.
function Encode.encodeCells(frame)
  local bytes, byteLen = Encode.encodeFrame(frame)
  local bits = bytesToBits(bytes, byteLen, STRIP.dataCells)
  local cells = {}
  for x = 0, STRIP.cols - 1 do
    cells[cellIndex(x, 0)] = (x % 2 == 0) and 1 or 0
  end
  for y = 1, STRIP.rows - 1 do
    cells[cellIndex(0, y)] = (y % 2 == 0) and 1 or 0
  end
  local i = 0
  for y = 1, STRIP.rows - 1 do
    for x = 1, STRIP.cols - 1 do
      i = i + 1
      cells[cellIndex(x, y)] = bits[i]
    end
  end
  return cells
end

-- Splits `text` (a Lua string; WoW addon files are UTF-8 and string.byte reads raw UTF-8 bytes, so
-- this needs no special encoding step) into frames of at most STRIP.payloadMax bytes each. Every
-- frame of one roster shares `rosterSeq` — exactly chunkRoster() in codec.ts.
function Encode.chunkRoster(text, rosterSeq)
  local len = #text
  local count = math.max(1, math.ceil(len / STRIP.payloadMax))
  if count > 255 then
    error(string.format("bmpl: roster too large: %d bytes needs %d chunks", len, count))
  end
  local frames = {}
  for i = 0, count - 1 do
    local startPos = i * STRIP.payloadMax + 1
    local endPos = math.min(len, startPos + STRIP.payloadMax - 1)
    local payload = {}
    local n = 0
    for p = startPos, endPos do
      n = n + 1
      payload[n] = string.byte(text, p)
    end
    frames[i + 1] = {
      version = STRIP.version,
      rosterSeq = rosterSeq % 65536,
      chunkIndex = i,
      chunkCount = count,
      payload = payload,
      payloadLen = n,
    }
  end
  return frames
end

-- Lower-case hex of a 1-indexed byte table, `len` bytes — for /bmpl selftest's output only.
function Encode.toHex(bytes, len)
  local parts = {}
  for i = 1, len do parts[i] = string.format("%02x", bytes[i]) end
  return table.concat(parts)
end
