-- addon/bmpl/main.lua
--
-- Wires the pieces together: the 20 Hz redraw loop, the visibility rule (Group Finder only, never
-- during a run), and the /bmpl slash commands. The addon sends nothing, receives nothing, stores
-- nothing — see addon/README.md.

local ADDON_NAME, ns = ...
local Encode, Strip, Roster, Cadence = ns.Encode, ns.Strip, ns.Roster, ns.Cadence

local UPDATE_INTERVAL = 0.05 -- 20 Hz

-- true once /bmpl show is used, until /bmpl hide releases it back to the automatic rule below.
local forcedOn = false

-- `text = nil` is the "nothing has been chunked yet" state, and it matters: Roster.BuildText() can
-- legitimately return "" (a solo player with no role assigned and no applicants), and with "" as the
-- initial value that empty roster would compare equal, leave `frames` empty, and leave whatever was
-- last painted on screen. The browser re-stamps a roster's freshness on any frame of a seq it already
-- holds, so a stale frame left up is a stale roster shown forever. nil can never compare equal, so the
-- first tick after every show always chunks and repaints — including the empty roster, which is a
-- legal one-frame payload the browser decodes as "nobody".
local roster = { text = nil, seq = 0, frames = {} }
local cadence = Cadence.new()

-- Visible only while the Group Finder is in play: its window is open, or the player has an active
-- Group Finder posting (so it keeps drawing while they alt-tab to the browser to review applicants
-- with the window closed) — never during a run. /bmpl show overrides this for troubleshooting.
local function shouldShow()
  if forcedOn then return true end
  local pve = _G.PVEFrame
  if pve and pve:IsShown() then return true end
  if C_LFGList and C_LFGList.GetActiveEntryInfo then
    local ok, activityID = pcall(C_LFGList.GetActiveEntryInfo)
    if ok and activityID ~= nil then return true end
  end
  return false
end

-- Returns true on the tick where the roster text actually changed — Cadence.step's `changed`.
local function rebuildRoster()
  local text = Roster.BuildText()
  if text == roster.text then return false end
  roster.text = text
  roster.seq = (roster.seq + 1) % 256
  local ok, frames = pcall(Encode.chunkRoster, text, roster.seq)
  roster.frames = ok and frames or {}
  return true
end

-- One 20 Hz tick: rebuild the roster text (a no-op when nothing changed), then ask Cadence whether to
-- repaint at all. It cycles the chunks for a few passes after a change and then leaves the strip
-- motionless, which is the whole point: a still patch is far easier to ignore than a flickering one,
-- and the browser keeps the roster alive off the frame that is already on screen.
local function tick(dt)
  if shouldShow() then
    local changed = rebuildRoster()
    Strip.Show()
    local index = Cadence.step(cadence, dt, #roster.frames, changed)
    if index then Strip.Paint(Encode.encodeCells(roster.frames[index])) end
  else
    Strip.Hide()
    roster.text, roster.frames = nil, {}
    cadence = Cadence.new()
  end
end

local driver = CreateFrame("Frame")
local sinceLast = 0
local sinceTick = 0
driver:SetScript("OnUpdate", function(_, delta)
  sinceLast = sinceLast + delta
  sinceTick = sinceTick + delta
  if sinceLast < UPDATE_INTERVAL then return end
  -- Subtract rather than zero: zeroing quantises the redraw to the game's frame period, which at 60 fps
  -- and a 0.05 s interval costs a third of the rate (~15 Hz instead of 20).
  sinceLast = sinceLast - UPDATE_INTERVAL
  if sinceLast > UPDATE_INTERVAL then sinceLast = 0 end -- after a long hitch, do not try to catch up.
  local dt = sinceTick -- real elapsed time, so the cadence's heartbeat stays honest across hitches.
  sinceTick = 0
  tick(dt)
end)

-- Only display events are registered, and they all mean the same thing: re-derive the cell's physical
-- size (PLAYER_ENTERING_WORLD because the effective UI scale at addon load is not always the final
-- one). The roster events — LFG_LIST_APPLICANT_LIST_UPDATED, LFG_LIST_ACTIVE_ENTRY_UPDATE,
-- GROUP_ROSTER_UPDATE — need no handler at all: the 20 Hz tick rebuilds the roster text every time and
-- only re-chunks it when the text differs, so a handler would have nothing left to do.
local events = CreateFrame("Frame")
events:RegisterEvent("PLAYER_ENTERING_WORLD")
events:RegisterEvent("UI_SCALE_CHANGED")
events:RegisterEvent("DISPLAY_SIZE_CHANGED")
events:SetScript("OnEvent", function()
  Strip.Rescale()
end)

-- ---------------------------------------------------------------------------------------------
-- /bmpl show | hide | selftest
-- ---------------------------------------------------------------------------------------------

-- The same three rosters as addon/bmpl/tests/vectors.txt (generated by scripts/live-vectors.ts from
-- web/src/lib/live/codec.ts) — the addon cannot read that file at runtime (no filesystem access in
-- the WoW addon sandbox), so this is a hand-copied snapshot. If codec.ts's framing ever changes,
-- regenerate vectors.txt and copy the new lines in here too: `test/live-vectors.test.ts` reads this
-- table out of main.lua and fails when it drifts from the .txt, so the copy cannot go stale silently.
-- `frames` pins the frame BYTES; `cells` pins the 16x10 LAYOUT of the first frame (marker row, marker
-- column, row-major MSB-first bits) — the part of Encode that only /bmpl selftest can check.
local SELFTEST_VECTORS = {
  {
    text = "a|Applicantone-Area52|1|T|1520\n",
    seq = 1,
    frames = {
      "b3010004096ba7617c4170706c696361",
      "b3010104094d846e746f6e652d417265",
      "b3010204098a376135327c317c547c31",
      "b301030404c6f13532300a",
    },
    cells = "aaaa5980c001012dba760be285c160d8e9633080",
  },
  {
    text = "a|Applicanttwo-Area52|7|H|1480\na|Applicantthree-Stormrage|4|D|1610\na|Applicantfour-Illidan|8|D|0\np|Partymember-Area52|11|T|1550\n",
    seq = 2,
    frames = {
      "b302000f09bab2617c4170706c696361",
      "b302010f0900f96e7474776f2d417265",
      "b302020f09dcd96135327c377c487c31",
      "b302030f0916043438300a617c417070",
      "b302040f096a6f6c6963616e74746872",
      "b302050f09c5fe65652d53746f726d72",
      "b302060f09aaf86167657c347c447c31",
      "b302070f09ac963631300a617c417070",
      "b302080f0965bd6c6963616e74666f75",
      "b302090f09483c722d496c6c6964616e",
      "b3020a0f0987277c387c447c300a707c",
      "b3020b0f0917e750617274796d656d62",
      "b3020c0f09bffd65722d417265613532",
      "b3020d0f095a567c31317c547c313535",
      "b3020e0f028181300a",
    },
    cells = "aaaa598180036137ab260be285c160d8e9633080",
  },
  {
    text = "a|Applicant01-Area52|4|T|1000\na|Applicant02-Area52|7|H|1010\na|Applicant03-Area52|4|D|1020\na|Applicant04-Area52|7|T|1030\na|Applicant05-Area52|4|H|1040\na|Applicant06-Area52|7|D|1050\na|Applicant07-Area52|4|T|1060\na|Applicant08-Area52|7|H|1070\na|Applicant09-Area52|4|D|1080\na|Applicant10-Area52|7|T|1090\na|Applicant11-Area52|4|H|1100\na|Applicant12-Area52|7|D|1110\na|Applicant13-Area52|4|T|1120\na|Applicant14-Area52|7|H|1130\na|Applicant15-Area52|4|D|1140\na|Applicant16-Area52|7|T|1150\na|Applicant17-Area52|4|H|1160\na|Applicant18-Area52|7|D|1170\na|Applicant19-Area52|4|T|1180\na|Applicant20-Area52|7|H|1190\n",
    seq = 255,
    frames = {
      "b3ff0043099e9a617c4170706c696361",
      "b3ff014309612f6e7430312d41726561",
      "b3ff024309d01335327c347c547c3130",
      "b3ff034309198930300a617c4170706c",
      "b3ff04430983b96963616e7430322d41",
      "b3ff0543095a6472656135327c377c48",
      "b3ff064309c4de7c313031300a617c41",
      "b3ff0743098b6b70706c6963616e7430",
      "b3ff084309b787332d4172656135327c",
      "b3ff094309c222347c447c313032300a",
      "b3ff0a4309dc87617c4170706c696361",
      "b3ff0b430922716e7430342d41726561",
      "b3ff0c4309a6cd35327c377c547c3130",
      "b3ff0d4309cbb433300a617c4170706c",
      "b3ff0e430951216963616e7430352d41",
      "b3ff0f4309482072656135327c347c48",
      "b3ff104309aba17c313034300a617c41",
      "b3ff114309e55770706c6963616e7430",
      "b3ff12430969da362d4172656135327c",
      "b3ff13430904a0377c447c313035300a",
      "b3ff1443091aa0617c4170706c696361",
      "b3ff15430904986e7430372d41726561",
      "b3ff164309542935327c347c547c3130",
      "b3ff17430915e936300a617c4170706c",
      "b3ff1843096e5f6963616e7430382d41",
      "b3ff194309764572656135327c377c48",
      "b3ff1a430909727c313037300a617c41",
      "b3ff1b4309a74a70706c6963616e7430",
      "b3ff1c4309ab52392d4172656135327c",
      "b3ff1d430987df347c447c313038300a",
      "b3ff1e430958bd617c4170706c696361",
      "b3ff1f430966f56e7431302d41726561",
      "b3ff2043097ab535327c377c547c3130",
      "b3ff2143098f2339300a617c4170706c",
      "b3ff224309f9f36963616e7431312d41",
      "b3ff234309945872656135327c347c48",
      "b3ff2443094f4b7c313130300a617c41",
      "b3ff254309e01370706c6963616e7431",
      "b3ff264309a212322d4172656135327c",
      "b3ff274309545e377c447c313131300a",
      "b3ff28430996ef617c4170706c696361",
      "b3ff29430948696e7431332d41726561",
      "b3ff2a4309f97635327c347c547c3131",
      "b3ff2b4309763a32300a617c4170706c",
      "b3ff2c43099f086963616e7431342d41",
      "b3ff2d4309521172656135327c377c48",
      "b3ff2e4309ed987c313133300a617c41",
      "b3ff2f4309a20e70706c6963616e7431",
      "b3ff304309679f352d4172656135327c",
      "b3ff3143098ea4347c447c313134300a",
      "b3ff32430984c5617c4170706c696361",
      "b3ff3343095b006e7431362d41726561",
      "b3ff344309df9f35327c377c547c3131",
      "b3ff3543091bac35300a617c4170706c",
      "b3ff364309dd7b6963616e7431372d41",
      "b3ff374309106272656135327c347c48",
      "b3ff38430982e77c313136300a617c41",
      "b3ff394309cc3270706c6963616e7431",
      "b3ff3a430916dc382d4172656135327c",
      "b3ff3b4309d8cd377c447c313137300a",
      "b3ff3c430912d5617c4170706c696361",
      "b3ff3d4309ced56e7431392d41726561",
      "b3ff3e43097d4c35327c347c547c3131",
      "b3ff3f43096aef38300a617c4170706c",
      "b3ff4043091fea6963616e7432302d41",
      "b3ff414309ceb472656135327c377c48",
      "b3ff42430654fc7c313139300a",
    },
    cells = "aaaa59ffc0106133e9a60be285c160d8e9633080",
  },
}

local function selftest()
  for _, vector in ipairs(SELFTEST_VECTORS) do
    local ok, frames = pcall(Encode.chunkRoster, vector.text, vector.seq)
    if not ok then
      print("bmpl selftest: FAILED — chunkRoster errored: " .. tostring(frames))
      return
    end
    if #frames ~= #vector.frames then
      print(string.format("bmpl selftest: FAILED — %d frames, expected %d", #frames, #vector.frames))
      return
    end
    for i, frame in ipairs(frames) do
      local bytes, len = Encode.encodeFrame(frame)
      local hex = Encode.toHex(bytes, len)
      if hex ~= vector.frames[i] then
        print("bmpl selftest: FAILED — mismatch on frame " .. i)
        print("  got:      " .. hex)
        print("  expected: " .. vector.frames[i])
        return
      end
    end
    -- The cell matrix of the first frame: the marker row/column and the MSB-first row-major bit
    -- placement, which the frame bytes above say nothing about.
    if vector.cells then
      local cellsOk, cells = pcall(Encode.encodeCells, frames[1])
      if not cellsOk then
        print("bmpl selftest: FAILED — encodeCells errored: " .. tostring(cells))
        return
      end
      local hex = Encode.cellsToHex(cells)
      if hex ~= vector.cells then
        print("bmpl selftest: FAILED — cell matrix mismatch")
        print("  got:      " .. hex)
        print("  expected: " .. vector.cells)
        return
      end
    end
  end
  print("OK")
end

-- /bmpl dump — print what the LFG API actually returns, so a roster that looks wrong on screen can be
-- diagnosed from the chat frame instead of guessed at. Reads only; prints nothing that is not already
-- visible in the Group Finder window.
-- The chat frame interprets "|" escapes (|c, |r, |n, |T…), so a raw roster line prints mangled —
-- "|R" vanishes, "|N" becomes a line break. Double every pipe before printing.
local function chatSafe(text)
  return (tostring(text):gsub("|", "||"))
end

-- Print an info table's own fields; the live client returns one where the documentation promises
-- multiple values, and the field names are what we have to read.
local function dumpTable(prefix, t)
  -- Keep the original keys: a stats table is keyed by number, and indexing it with tostring(k)
  -- printed nil for every entry.
  local keys = {}
  for k in pairs(t) do keys[#keys + 1] = k end
  table.sort(keys, function(x, y) return tostring(x) < tostring(y) end)
  for _, k in ipairs(keys) do
    local v = t[k]
    if type(v) == "table" then
      print(string.format("%s%s = table:", prefix, tostring(k)))
      for k2, v2 in pairs(v) do
        print(string.format("%s  %s = %s", prefix, tostring(k2), chatSafe(v2)))
      end
    else
      print(string.format("%s%s = %s", prefix, tostring(k), chatSafe(v)))
    end
  end
end

local function dump()
  if not C_LFGList or not C_LFGList.GetApplicants then
    print("bmpl dump: C_LFGList.GetApplicants is missing")
    return
  end
  local ok, ids = pcall(C_LFGList.GetApplicants)
  if not ok or not ids then
    print("bmpl dump: GetApplicants failed: " .. tostring(ids))
    return
  end
  print(string.format("bmpl dump: %d application(s)", #ids))
  for _, id in ipairs(ids) do
    local infoOk, a, b, c, d, e, f, g = pcall(C_LFGList.GetApplicantInfo, id)
    if not infoOk then
      print(string.format("  id=%s → GetApplicantInfo failed: %s", tostring(id), chatSafe(a)))
    elseif type(a) == "table" then
      print(string.format("  id=%s → info table:", tostring(id)))
      dumpTable("      ", a)
    else
      print(string.format("  id=%s → 1=%s 2=%s 3=%s 4=%s 5=%s 6=%s 7=%s", tostring(id),
        chatSafe(a), chatSafe(b), chatSafe(c), chatSafe(d), chatSafe(e), chatSafe(f), chatSafe(g)))
    end
    for i = 1, 3 do
      local memberOk, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15 =
        pcall(C_LFGList.GetApplicantMemberInfo, id, i)
      if not memberOk then
        print(string.format("    member %d: call failed: %s", i, chatSafe(m2)))
      elseif m2 == nil then
        print(string.format("    member %d: nil", i))
      elseif type(m2) == "table" then
        print(string.format("    member %d: info table:", i))
        dumpTable("        ", m2)
      elseif true then
        print(string.format("    member %d: %s %s %s %s %s %s %s %s %s %s %s %s %s %s", i,
          chatSafe(m2), chatSafe(m3), chatSafe(m4), chatSafe(m5), chatSafe(m6), chatSafe(m7),
          chatSafe(m8), chatSafe(m9), chatSafe(m10), chatSafe(m11), chatSafe(m12), chatSafe(m13),
          chatSafe(m14), chatSafe(m15)))
      end
      -- Where the Mythic+ rating actually lives on this client: the positional dungeonScore reads 0
      -- for everyone, so print whatever the stats API exposes for the same member.
      if C_LFGList.GetApplicantMemberStats then
        local statsOk, stats = pcall(C_LFGList.GetApplicantMemberStats, id, i)
        if statsOk and type(stats) == "table" then
          local n = 0
          for _ in pairs(stats) do n = n + 1 end
          if n > 0 then
            print(string.format("      stats(%d):", i))
            dumpTable("        ", stats)
          end
        elseif statsOk and stats ~= nil then
          print(string.format("      stats(%d) = %s", i, chatSafe(stats)))
        end
      end
    end
  end
  local text = Roster.BuildText and Roster.BuildText() or ""
  print("bmpl dump: roster text the strip carries —")
  for line in tostring(text):gmatch("[^\n]+") do print("  " .. chatSafe(line)) end
end

SLASH_BMPL1 = "/bmpl"
SlashCmdList.BMPL = function(msg)
  msg = (msg or ""):lower():match("^%s*(.-)%s*$")
  if msg == "show" then
    forcedOn = true
    Strip.Rescale()
    print("bmpl: strip forced on — /bmpl hide to release it")
  elseif msg == "hide" then
    forcedOn = false
    print("bmpl: back to automatic (Group Finder open, or an active posting)")
  elseif msg == "selftest" then
    selftest()
  elseif msg == "dump" then
    dump()
  elseif msg:match("^cell%s") or msg == "cell" then
    local applied = Strip.SetCell(msg:match("^cell%s+(%d+)$"))
    if applied then
      print(string.format("bmpl: cell size %d px (strip is %dx%d px) — /reload restores the default",
        applied, Encode.STRIP.cols * applied, Encode.STRIP.rows * applied))
    else
      print(string.format("bmpl: /bmpl cell <3-10> — currently %d px", Strip.Cell()))
    end
  elseif msg:match("^contrast%s") or msg == "contrast" then
    local applied = Strip.SetContrast(msg:match("^contrast%s+(%a+)$"))
    if applied then
      -- Force the next tick to re-chunk and repaint, so the new levels appear at once instead of
      -- waiting for the roster to change or for the cadence's heartbeat. nil, not "": an empty roster
      -- text is a real value that would compare equal and repaint nothing.
      roster.text = nil
      print(string.format("bmpl: contrast %s — /reload restores the default (dim)", applied))
    else
      print(string.format("bmpl: /bmpl contrast dim|full — currently %s", Strip.Contrast()))
    end
  else
    print("bmpl: /bmpl show | hide | selftest | dump | cell <3-10> | contrast dim|full")
  end
end
