-- addon/bmpl/main.lua
--
-- Wires the pieces together: the 20 Hz redraw loop, the visibility rule (Group Finder only, never
-- during a run), and the /bmpl slash commands. The addon sends nothing, receives nothing, stores
-- nothing — see addon/README.md.

local ADDON_NAME, ns = ...
local Encode, Strip, Roster, Cadence = ns.Encode, ns.Strip, ns.Roster, ns.Cadence

local UPDATE_INTERVAL = 0.05 -- 20 Hz

-- true once /bmpl show is used, until /bmpl hide releases it back to the automatic rule below.
local forcedOn = false

local roster = { text = "", seq = 0, frames = {} }
local cadence = Cadence.new()

-- Visible only while the Group Finder is in play: its window is open, or the player has an active
-- Group Finder posting (so it keeps drawing while they alt-tab to the browser to review applicants
-- with the window closed) — never during a run. /bmpl show overrides this for troubleshooting.
local function shouldShow()
  if forcedOn then return true end
  local pve = _G.PVEFrame
  if pve and pve:IsShown() then return true end
  if C_LFGList and C_LFGList.GetActiveEntryInfo then
    local ok, activityID = pcall(C_LFGList.GetActiveEntryInfo)
    if ok and activityID ~= nil then return true end
  end
  return false
end

-- Returns true on the tick where the roster text actually changed — Cadence.step's `changed`.
local function rebuildRoster()
  local text = Roster.BuildText()
  if text == roster.text then return false end
  roster.text = text
  roster.seq = (roster.seq + 1) % 256
  local ok, frames = pcall(Encode.chunkRoster, text, roster.seq)
  roster.frames = ok and frames or {}
  return true
end

-- One 20 Hz tick: rebuild the roster text (a no-op when nothing changed), then ask Cadence whether to
-- repaint at all. It cycles the chunks for a few passes after a change and then leaves the strip
-- motionless, which is the whole point: a still patch is far easier to ignore than a flickering one,
-- and the browser keeps the roster alive off the frame that is already on screen.
local function tick(dt)
  if shouldShow() then
    local changed = rebuildRoster()
    Strip.Show()
    local index = Cadence.step(cadence, dt, #roster.frames, changed)
    if index then Strip.Paint(Encode.encodeCells(roster.frames[index])) end
  else
    Strip.Hide()
    roster.text, roster.frames = "", {}
    cadence = Cadence.new()
  end
end

local driver = CreateFrame("Frame")
local sinceLast = 0
local sinceTick = 0
driver:SetScript("OnUpdate", function(_, delta)
  sinceLast = sinceLast + delta
  sinceTick = sinceTick + delta
  if sinceLast < UPDATE_INTERVAL then return end
  -- Subtract rather than zero: zeroing quantises the redraw to the game's frame period, which at 60 fps
  -- and a 0.05 s interval costs a third of the rate (~15 Hz instead of 20).
  sinceLast = sinceLast - UPDATE_INTERVAL
  if sinceLast > UPDATE_INTERVAL then sinceLast = 0 end -- after a long hitch, do not try to catch up.
  local dt = sinceTick -- real elapsed time, so the cadence's heartbeat stays honest across hitches.
  sinceTick = 0
  tick(dt)
end)

-- Only display events are registered, and they all mean the same thing: re-derive the cell's physical
-- size (PLAYER_ENTERING_WORLD because the effective UI scale at addon load is not always the final
-- one). The roster events — LFG_LIST_APPLICANT_LIST_UPDATED, LFG_LIST_ACTIVE_ENTRY_UPDATE,
-- GROUP_ROSTER_UPDATE — need no handler at all: the 20 Hz tick rebuilds the roster text every time and
-- only re-chunks it when the text differs, so a handler would have nothing left to do.
local events = CreateFrame("Frame")
events:RegisterEvent("PLAYER_ENTERING_WORLD")
events:RegisterEvent("UI_SCALE_CHANGED")
events:RegisterEvent("DISPLAY_SIZE_CHANGED")
events:SetScript("OnEvent", function()
  Strip.Rescale()
end)

-- ---------------------------------------------------------------------------------------------
-- /bmpl show | hide | selftest
-- ---------------------------------------------------------------------------------------------

-- The same three rosters as addon/bmpl/tests/vectors.txt (generated by scripts/live-vectors.ts from
-- web/src/lib/live/codec.ts) — the addon cannot read that file at runtime (no filesystem access in
-- the WoW addon sandbox), so this is a hand-copied snapshot. If codec.ts's framing ever changes,
-- regenerate vectors.txt and copy the new lines in here too: `test/live-vectors.test.ts` reads this
-- table out of main.lua and fails when it drifts from the .txt, so the copy cannot go stale silently.
-- `frames` pins the frame BYTES; `cells` pins the 24x10 LAYOUT of the first frame (marker row, marker
-- column, row-major MSB-first bits) — the part of Encode that only /bmpl selftest can check.
local SELFTEST_VECTORS = {
  {
    text = "a|Applicantone-Area52|1|T|1520\n",
    seq = 1,
    frames = {
      "b201000212ad66617c4170706c6963616e746f6e652d417265",
      "b20101020d5b2d6135327c317c547c313532300a",
    },
    cells = "aaaaaa5900808084ab2ccc2fc4170703634b8d85b968dedce52d41393280",
  },
  {
    text = "a|Applicanttwo-Area52|7|H|1480\na|Applicantthree-Stormrage|4|D|1610\na|Applicantfour-Illidan|8|D|0\np|Partymember-Area52|11|T|1550\n",
    seq = 2,
    frames = {
      "b202000812866e617c4170706c6963616e7474776f2d417265",
      "b202010812ac0a6135327c377c487c313438300a617c417070",
      "b202020812a2636c6963616e7474687265652d53746f726d72",
      "b202030812ac356167657c347c447c313631300a617c417070",
      "b202040812d86f6c6963616e74666f75722d496c6c6964616e",
      "b2020508121d207c387c447c300a707c50617274796d656d62",
      "b202060812282c65722d4172656135327c31317c547c313535",
      "b202070802b1c0300a",
    },
    cells = "aaaaaa5901008204a14dcc2fc4170703634b8d85b968e8eeef2d41393280",
  },
  {
    text = "a|Applicant01-Area52|4|T|1000\na|Applicant02-Area52|7|H|1010\na|Applicant03-Area52|4|D|1020\na|Applicant04-Area52|7|T|1030\na|Applicant05-Area52|4|H|1040\na|Applicant06-Area52|7|D|1050\na|Applicant07-Area52|4|T|1060\na|Applicant08-Area52|7|H|1070\na|Applicant09-Area52|4|D|1080\na|Applicant10-Area52|7|T|1090\na|Applicant11-Area52|4|H|1100\na|Applicant12-Area52|7|D|1110\na|Applicant13-Area52|4|T|1120\na|Applicant14-Area52|7|H|1130\na|Applicant15-Area52|4|D|1140\na|Applicant16-Area52|7|T|1150\na|Applicant17-Area52|4|H|1160\na|Applicant18-Area52|7|D|1170\na|Applicant19-Area52|4|T|1180\na|Applicant20-Area52|7|H|1190\n",
    seq = 255,
    frames = {
      "b2ff002212a4bc617c4170706c6963616e7430312d41726561",
      "b2ff012212a26735327c347c547c313030300a617c4170706c",
      "b2ff02221255c76963616e7430322d4172656135327c377c48",
      "b2ff03221213d87c313031300a617c4170706c6963616e7430",
      "b2ff042212ce2d332d4172656135327c347c447c313032300a",
      "b2ff052212e84d617c4170706c6963616e7430342d41726561",
      "b2ff06221243a035327c377c547c313033300a617c4170706c",
      "b2ff07221203246963616e7430352d4172656135327c347c48",
      "b2ff082212104c7c313034300a617c4170706c6963616e7430",
      "b2ff092212b7f8362d4172656135327c377c447c313035300a",
      "b2ff0a2212fe45617c4170706c6963616e7430372d41726561",
      "b2ff0b2212914935327c347c547c313036300a617c4170706c",
      "b2ff0c221217c96963616e7430382d4172656135327c377c48",
      "b2ff0d2212781d7c313037300a617c4170706c6963616e7430",
      "b2ff0e2212989f392d4172656135327c347c447c313038300a",
      "b2ff0f22129387617c4170706c6963616e7431302d41726561",
      "b2ff102212601d35327c377c547c313039300a617c4170706c",
      "b2ff1122120f3e6963616e7431312d4172656135327c347c48",
      "b2ff122212d1957c313130300a617c4170706c6963616e7431",
      "b2ff1322121258322d4172656135327c377c447c313131300a",
      "b2ff142212f366617c4170706c6963616e7431332d41726561",
      "b2ff152212f62735327c347c547c313132300a617c4170706c",
      "b2ff1622127e606963616e7431342d4172656135327c377c48",
      "b2ff172212b9c47c313133300a617c4170706c6963616e7431",
      "b2ff1822123ecf352d4172656135327c347c447c313134300a",
      "b2ff192212c958617c4170706c6963616e7431362d41726561",
      "b2ff1a22128eb335327c377c547c313135300a617c4170706c",
      "b2ff1b22128a416963616e7431372d4172656135327c347c48",
      "b2ff1c2212ba507c313136300a617c4170706c6963616e7431",
      "b2ff1d22129ef8382d4172656135327c377c447c313137300a",
      "b2ff1e22124a94617c4170706c6963616e7431392d41726561",
      "b2ff1f2212d5bc35327c347c547c313138300a617c4170706c",
      "b2ff2022120ffd6963616e7432302d4172656135327c377c48",
      "b2ff212206173b7c313139300a",
    },
    cells = "aaaaaa597f808884a9178c2fc4170703634b8d85b9686062ad417232b080",
  },
}

local function selftest()
  for _, vector in ipairs(SELFTEST_VECTORS) do
    local ok, frames = pcall(Encode.chunkRoster, vector.text, vector.seq)
    if not ok then
      print("bmpl selftest: FAILED — chunkRoster errored: " .. tostring(frames))
      return
    end
    if #frames ~= #vector.frames then
      print(string.format("bmpl selftest: FAILED — %d frames, expected %d", #frames, #vector.frames))
      return
    end
    for i, frame in ipairs(frames) do
      local bytes, len = Encode.encodeFrame(frame)
      local hex = Encode.toHex(bytes, len)
      if hex ~= vector.frames[i] then
        print("bmpl selftest: FAILED — mismatch on frame " .. i)
        print("  got:      " .. hex)
        print("  expected: " .. vector.frames[i])
        return
      end
    end
    -- The cell matrix of the first frame: the marker row/column and the MSB-first row-major bit
    -- placement, which the frame bytes above say nothing about.
    if vector.cells then
      local cellsOk, cells = pcall(Encode.encodeCells, frames[1])
      if not cellsOk then
        print("bmpl selftest: FAILED — encodeCells errored: " .. tostring(cells))
        return
      end
      local hex = Encode.cellsToHex(cells)
      if hex ~= vector.cells then
        print("bmpl selftest: FAILED — cell matrix mismatch")
        print("  got:      " .. hex)
        print("  expected: " .. vector.cells)
        return
      end
    end
  end
  print("OK")
end

-- /bmpl dump — print what the LFG API actually returns, so a roster that looks wrong on screen can be
-- diagnosed from the chat frame instead of guessed at. Reads only; prints nothing that is not already
-- visible in the Group Finder window.
-- The chat frame interprets "|" escapes (|c, |r, |n, |T…), so a raw roster line prints mangled —
-- "|R" vanishes, "|N" becomes a line break. Double every pipe before printing.
local function chatSafe(text)
  return (tostring(text):gsub("|", "||"))
end

-- Print an info table's own fields; the live client returns one where the documentation promises
-- multiple values, and the field names are what we have to read.
local function dumpTable(prefix, t)
  -- Keep the original keys: a stats table is keyed by number, and indexing it with tostring(k)
  -- printed nil for every entry.
  local keys = {}
  for k in pairs(t) do keys[#keys + 1] = k end
  table.sort(keys, function(x, y) return tostring(x) < tostring(y) end)
  for _, k in ipairs(keys) do
    local v = t[k]
    if type(v) == "table" then
      print(string.format("%s%s = table:", prefix, tostring(k)))
      for k2, v2 in pairs(v) do
        print(string.format("%s  %s = %s", prefix, tostring(k2), chatSafe(v2)))
      end
    else
      print(string.format("%s%s = %s", prefix, tostring(k), chatSafe(v)))
    end
  end
end

local function dump()
  if not C_LFGList or not C_LFGList.GetApplicants then
    print("bmpl dump: C_LFGList.GetApplicants is missing")
    return
  end
  local ok, ids = pcall(C_LFGList.GetApplicants)
  if not ok or not ids then
    print("bmpl dump: GetApplicants failed: " .. tostring(ids))
    return
  end
  print(string.format("bmpl dump: %d application(s)", #ids))
  for _, id in ipairs(ids) do
    local infoOk, a, b, c, d, e, f, g = pcall(C_LFGList.GetApplicantInfo, id)
    if not infoOk then
      print(string.format("  id=%s → GetApplicantInfo failed: %s", tostring(id), chatSafe(a)))
    elseif type(a) == "table" then
      print(string.format("  id=%s → info table:", tostring(id)))
      dumpTable("      ", a)
    else
      print(string.format("  id=%s → 1=%s 2=%s 3=%s 4=%s 5=%s 6=%s 7=%s", tostring(id),
        chatSafe(a), chatSafe(b), chatSafe(c), chatSafe(d), chatSafe(e), chatSafe(f), chatSafe(g)))
    end
    for i = 1, 3 do
      local memberOk, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15 =
        pcall(C_LFGList.GetApplicantMemberInfo, id, i)
      if not memberOk then
        print(string.format("    member %d: call failed: %s", i, chatSafe(m2)))
      elseif m2 == nil then
        print(string.format("    member %d: nil", i))
      elseif type(m2) == "table" then
        print(string.format("    member %d: info table:", i))
        dumpTable("        ", m2)
      elseif true then
        print(string.format("    member %d: %s %s %s %s %s %s %s %s %s %s %s %s %s %s", i,
          chatSafe(m2), chatSafe(m3), chatSafe(m4), chatSafe(m5), chatSafe(m6), chatSafe(m7),
          chatSafe(m8), chatSafe(m9), chatSafe(m10), chatSafe(m11), chatSafe(m12), chatSafe(m13),
          chatSafe(m14), chatSafe(m15)))
      end
      -- Where the Mythic+ rating actually lives on this client: the positional dungeonScore reads 0
      -- for everyone, so print whatever the stats API exposes for the same member.
      if C_LFGList.GetApplicantMemberStats then
        local statsOk, stats = pcall(C_LFGList.GetApplicantMemberStats, id, i)
        if statsOk and type(stats) == "table" then
          local n = 0
          for _ in pairs(stats) do n = n + 1 end
          if n > 0 then
            print(string.format("      stats(%d):", i))
            dumpTable("        ", stats)
          end
        elseif statsOk and stats ~= nil then
          print(string.format("      stats(%d) = %s", i, chatSafe(stats)))
        end
      end
    end
  end
  local text = Roster.BuildText and Roster.BuildText() or ""
  print("bmpl dump: roster text the strip carries —")
  for line in tostring(text):gmatch("[^\n]+") do print("  " .. chatSafe(line)) end
end

SLASH_BMPL1 = "/bmpl"
SlashCmdList.BMPL = function(msg)
  msg = (msg or ""):lower():match("^%s*(.-)%s*$")
  if msg == "show" then
    forcedOn = true
    Strip.Rescale()
    print("bmpl: strip forced on — /bmpl hide to release it")
  elseif msg == "hide" then
    forcedOn = false
    print("bmpl: back to automatic (Group Finder open, or an active posting)")
  elseif msg == "selftest" then
    selftest()
  elseif msg == "dump" then
    dump()
  elseif msg:match("^cell%s") or msg == "cell" then
    local applied = Strip.SetCell(msg:match("^cell%s+(%d+)$"))
    if applied then
      print(string.format("bmpl: cell size %d px (strip is %dx%d px) — /reload restores the default",
        applied, Encode.STRIP.cols * applied, Encode.STRIP.rows * applied))
    else
      print(string.format("bmpl: /bmpl cell <3-10> — currently %d px", Strip.Cell()))
    end
  elseif msg:match("^contrast%s") or msg == "contrast" then
    local applied = Strip.SetContrast(msg:match("^contrast%s+(%a+)$"))
    if applied then
      -- Force the next tick to re-chunk and repaint, so the new levels appear at once instead of
      -- waiting for the roster to change or for the cadence's heartbeat.
      roster.text = ""
      print(string.format("bmpl: contrast %s — /reload restores the default (dim)", applied))
    else
      print(string.format("bmpl: /bmpl contrast dim|full — currently %s", Strip.Contrast()))
    end
  else
    print("bmpl: /bmpl show | hide | selftest | dump | cell <3-10> | contrast dim|full")
  end
end
