-- addon/bmpl/main.lua
--
-- Wires the pieces together: the 10 Hz redraw loop, the visibility rule (Group Finder only, never
-- during a run), and the /bmpl slash commands. The addon sends nothing, receives nothing, stores
-- nothing — see addon/README.md.

local ADDON_NAME, ns = ...
local Encode, Strip, Roster = ns.Encode, ns.Strip, ns.Roster

local UPDATE_INTERVAL = 0.1 -- 10 Hz

-- true once /bmpl show is used, until /bmpl hide releases it back to the automatic rule below.
local forcedOn = false

local roster = { text = "", seq = 0, frames = {}, cursor = 0 }

-- Visible only while the Group Finder is in play: its window is open, or the player has an active
-- Group Finder posting (so it keeps drawing while they alt-tab to the browser to review applicants
-- with the window closed) — never during a run. /bmpl show overrides this for troubleshooting.
local function shouldShow()
  if forcedOn then return true end
  local pve = _G.PVEFrame
  if pve and pve:IsShown() then return true end
  if C_LFGList and C_LFGList.GetActiveEntryInfo then
    local ok, activityID = pcall(C_LFGList.GetActiveEntryInfo)
    if ok and activityID ~= nil then return true end
  end
  return false
end

local function rebuildRoster()
  local text = Roster.BuildText()
  if text == roster.text then return end
  roster.text = text
  roster.seq = (roster.seq + 1) % 65536
  local ok, frames = pcall(Encode.chunkRoster, text, roster.seq)
  roster.frames = ok and frames or {}
  roster.cursor = 0
end

-- One 10 Hz tick: rebuild the roster text (a no-op when nothing changed), keep asking the client to
-- inspect any un-resolved party member, and paint the next frame — cycling through every chunk of a
-- multi-frame roster so the browser's scanner (also 10 Hz) can assemble the whole thing over a few
-- ticks; a single-frame roster (the common case) just redraws itself every tick.
local function tick()
  if shouldShow() then
    rebuildRoster()
    Roster.RequestPartyInspects()
    Strip.Show()
    local frames = roster.frames
    if #frames > 0 then
      roster.cursor = (roster.cursor % #frames) + 1
      Strip.Paint(Encode.encodeCells(frames[roster.cursor]))
    end
  else
    Strip.Hide()
    roster.text, roster.frames, roster.cursor = "", {}, 0
  end
end

local driver = CreateFrame("Frame")
local sinceLast = 0
driver:SetScript("OnUpdate", function(_, delta)
  sinceLast = sinceLast + delta
  if sinceLast < UPDATE_INTERVAL then return end
  sinceLast = 0
  tick()
end)

local events = CreateFrame("Frame")
events:RegisterEvent("PLAYER_ENTERING_WORLD")
events:RegisterEvent("LFG_LIST_APPLICANT_LIST_UPDATED")
events:RegisterEvent("LFG_LIST_ACTIVE_ENTRY_UPDATE")
events:RegisterEvent("GROUP_ROSTER_UPDATE")
events:RegisterEvent("INSPECT_READY")
events:RegisterEvent("PLAYER_SPECIALIZATION_CHANGED")
events:RegisterEvent("UI_SCALE_CHANGED")
events:RegisterEvent("DISPLAY_SIZE_CHANGED")
events:SetScript("OnEvent", function(_, event, ...)
  if event == "INSPECT_READY" then
    Roster.HandleInspectReady(...)
  elseif event == "PLAYER_SPECIALIZATION_CHANGED" then
    Roster.ForgetPartySpecs(...) -- the event's unitTarget, or nil: drop that member's cached spec (or all of them)
  elseif event == "GROUP_ROSTER_UPDATE" then
    Roster.PrunePartySpecs() -- ... and forget whoever left, so a recycled slot never inherits a spec
  elseif event == "UI_SCALE_CHANGED" or event == "DISPLAY_SIZE_CHANGED" then
    Strip.Rescale()
  end
  -- Every other registered event just means "the roster might have changed"; the next 10 Hz tick
  -- picks it up on its own via rebuildRoster()'s text diff, so there is nothing else to do here.
end)

-- ---------------------------------------------------------------------------------------------
-- /bmpl show | hide | selftest
-- ---------------------------------------------------------------------------------------------

-- The same three rosters as addon/bmpl/tests/vectors.txt (generated by scripts/live-vectors.ts from
-- web/src/lib/live/codec.ts) — the addon cannot read that file at runtime (no filesystem access in
-- the WoW addon sandbox), so this is a hand-copied snapshot. If codec.ts's framing ever changes,
-- regenerate vectors.txt and copy the new lines in here too: `test/live-vectors.test.ts` reads this
-- table out of main.lua and fails when it drifts from the .txt, so the copy cannot go stale silently.
-- `frames` pins the frame BYTES; `cells` pins the 40x16 LAYOUT of the first frame (marker row, marker
-- column, row-major MSB-first bits) — the part of Encode that only /bmpl selftest can check.
local SELFTEST_VECTORS = {
  {
    text = "a|Applicantone-Area52|DeathKnight|Blood|T|1520\n",
    seq = 1,
    frames = { "626d706c01010000012fc3b3617c4170706c6963616e746f6e652d4172656135327c44656174684b6e696768747c426c6f6f647c547c313532300a" },
    cells = "aaaaaaaaaa3136b83600c04000004b78766c2f88970706c6961b0b73a37bb994b505c94ac26a64f8c46561746825b734b3b49d1f109b1b6dec8f8a8fc313532300500000000080000000000000000000",
  },
  {
    text = "a|Applicanttwo-Area52|Priest|Holy|H|1480\na|Applicantthree-Stormrage|Mage|Frost|D|1610\na|Applicantfour-Illidan|Rogue|Assassination|D|0\np|Partymember-Area52|Warrior|Protection|T|1550\n",
    seq = 2,
    frames = {
      "626d706c01020000033da54d617c4170706c6963616e7474776f2d4172656135327c5072696573747c486f6c797c487c313438300a617c4170706c6963616e7474687265652d53746f",
      "626d706c01020001033d2090726d726167657c4d6167657c46726f73747c447c313631300a617c4170706c6963616e74666f75722d496c6c6964616e7c526f6775657c417373617373",
      "626d706c01020002033b5381696e6174696f6e7c447c300a707c50617274796d656d6265722d4172656135327c57617272696f727c50726f74656374696f6e7c547c313535300a",
    },
    cells = "aaaaaaaaaa3136b83600c0800000cf34a9ac2f88970706c6961b0b73a3a3ddbcb505c94ac26a64f8d0726965733a3e2437b69e5f121f0c268706014c97c4170706634b1b0b73d1d1a1c9954a5aa6e8de",
  },
  {
    text = "a|Applicant01-Area52|Mage|Frost|T|1000\na|Applicant02-Area52|Priest|Holy|H|1010\na|Applicant03-Area52|Mage|Frost|D|1020\na|Applicant04-Area52|Priest|Holy|T|1030\na|Applicant05-Area52|Mage|Frost|H|1040\na|Applicant06-Area52|Priest|Holy|D|1050\na|Applicant07-Area52|Mage|Frost|T|1060\na|Applicant08-Area52|Priest|Holy|H|1070\na|Applicant09-Area52|Mage|Frost|D|1080\na|Applicant10-Area52|Priest|Holy|T|1090\na|Applicant11-Area52|Mage|Frost|H|1100\na|Applicant12-Area52|Priest|Holy|D|1110\na|Applicant13-Area52|Mage|Frost|T|1120\na|Applicant14-Area52|Priest|Holy|H|1130\na|Applicant15-Area52|Mage|Frost|D|1140\na|Applicant16-Area52|Priest|Holy|T|1150\na|Applicant17-Area52|Mage|Frost|H|1160\na|Applicant18-Area52|Priest|Holy|D|1170\na|Applicant19-Area52|Mage|Frost|T|1180\na|Applicant20-Area52|Priest|Holy|H|1190\n",
    seq = 65535,
    frames = {
      "626d706c01ffff000d3d067c617c4170706c6963616e7430312d4172656135327c4d6167657c46726f73747c547c313030300a617c4170706c6963616e7430322d4172656135327c50",
      "626d706c01ffff010d3da0ea72696573747c486f6c797c487c313031300a617c4170706c6963616e7430332d4172656135327c4d6167657c46726f73747c447c313032300a617c4170",
      "626d706c01ffff020d3d9225706c6963616e7430342d4172656135327c5072696573747c486f6c797c547c313033300a617c4170706c6963616e7430352d4172656135327c4d616765",
      "626d706c01ffff030d3dcfca7c46726f73747c487c313034300a617c4170706c6963616e7430362d4172656135327c5072696573747c486f6c797c447c313035300a617c4170706c69",
      "626d706c01ffff040d3dc77c63616e7430372d4172656135327c4d6167657c46726f73747c547c313036300a617c4170706c6963616e7430382d4172656135327c5072696573747c48",
      "626d706c01ffff050d3d39526f6c797c487c313037300a617c4170706c6963616e7430392d4172656135327c4d6167657c46726f73747c447c313038300a617c4170706c6963616e74",
      "626d706c01ffff060d3d927c31302d4172656135327c5072696573747c486f6c797c547c313039300a617c4170706c6963616e7431312d4172656135327c4d6167657c46726f73747c",
      "626d706c01ffff070d3d6a2e487c313130300a617c4170706c6963616e7431322d4172656135327c5072696573747c486f6c797c447c313131300a617c4170706c6963616e7431332d",
      "626d706c01ffff080d3d74db4172656135327c4d6167657c46726f73747c547c313132300a617c4170706c6963616e7431342d4172656135327c5072696573747c486f6c797c487c31",
      "626d706c01ffff090d3d3d143133300a617c4170706c6963616e7431352d4172656135327c4d6167657c46726f73747c447c313134300a617c4170706c6963616e7431362d41726561",
      "626d706c01ffff0a0d3d71c035327c5072696573747c486f6c797c547c313135300a617c4170706c6963616e7431372d4172656135327c4d6167657c46726f73747c487c313136300a",
      "626d706c01ffff0b0d3d234c617c4170706c6963616e7431382d4172656135327c5072696573747c486f6c797c447c313137300a617c4170706c6963616e7431392d4172656135327c",
      "626d706c01ffff0c0d3ac73a4d6167657c46726f73747c547c313138300a617c4170706c6963616e7432302d4172656135327c5072696573747c486f6c797c487c313139300a",
    },
    cells = "aaaaaaaaaa3136b83600ffffc0034f20cf8c2f88970706c6961b0b73a181c4b505c995426a64f89ae167657c463937b9ba3e951f0c4c0c06014c2f88970706c6961b0b73a181c8b505c995426a64f8a0",
  },
}

local function selftest()
  for _, vector in ipairs(SELFTEST_VECTORS) do
    local ok, frames = pcall(Encode.chunkRoster, vector.text, vector.seq)
    if not ok then
      print("bmpl selftest: FAILED — chunkRoster errored: " .. tostring(frames))
      return
    end
    if #frames ~= #vector.frames then
      print(string.format("bmpl selftest: FAILED — %d frames, expected %d", #frames, #vector.frames))
      return
    end
    for i, frame in ipairs(frames) do
      local bytes, len = Encode.encodeFrame(frame)
      local hex = Encode.toHex(bytes, len)
      if hex ~= vector.frames[i] then
        print("bmpl selftest: FAILED — mismatch on frame " .. i)
        print("  got:      " .. hex)
        print("  expected: " .. vector.frames[i])
        return
      end
    end
    -- The cell matrix of the first frame: the marker row/column and the MSB-first row-major bit
    -- placement, which the frame bytes above say nothing about.
    if vector.cells then
      local cellsOk, cells = pcall(Encode.encodeCells, frames[1])
      if not cellsOk then
        print("bmpl selftest: FAILED — encodeCells errored: " .. tostring(cells))
        return
      end
      local hex = Encode.cellsToHex(cells)
      if hex ~= vector.cells then
        print("bmpl selftest: FAILED — cell matrix mismatch")
        print("  got:      " .. hex)
        print("  expected: " .. vector.cells)
        return
      end
    end
  end
  print("OK")
end

-- /bmpl dump — print what the LFG API actually returns, so a roster that looks wrong on screen can be
-- diagnosed from the chat frame instead of guessed at. Reads only; prints nothing that is not already
-- visible in the Group Finder window.
-- The chat frame interprets "|" escapes (|c, |r, |n, |T…), so a raw roster line prints mangled —
-- "|R" vanishes, "|N" becomes a line break. Double every pipe before printing.
local function chatSafe(text)
  return (tostring(text):gsub("|", "||"))
end

-- Print an info table's own fields; the live client returns one where the documentation promises
-- multiple values, and the field names are what we have to read.
local function dumpTable(prefix, t)
  local keys = {}
  for k in pairs(t) do keys[#keys + 1] = tostring(k) end
  table.sort(keys)
  for _, k in ipairs(keys) do
    print(string.format("%s%s = %s", prefix, k, chatSafe(t[k])))
  end
end

local function dump()
  if not C_LFGList or not C_LFGList.GetApplicants then
    print("bmpl dump: C_LFGList.GetApplicants is missing")
    return
  end
  local ok, ids = pcall(C_LFGList.GetApplicants)
  if not ok or not ids then
    print("bmpl dump: GetApplicants failed: " .. tostring(ids))
    return
  end
  print(string.format("bmpl dump: %d application(s)", #ids))
  for _, id in ipairs(ids) do
    local infoOk, a, b, c, d, e, f, g = pcall(C_LFGList.GetApplicantInfo, id)
    if not infoOk then
      print(string.format("  id=%s → GetApplicantInfo failed: %s", tostring(id), chatSafe(a)))
    elseif type(a) == "table" then
      print(string.format("  id=%s → info table:", tostring(id)))
      dumpTable("      ", a)
    else
      print(string.format("  id=%s → 1=%s 2=%s 3=%s 4=%s 5=%s 6=%s 7=%s", tostring(id),
        chatSafe(a), chatSafe(b), chatSafe(c), chatSafe(d), chatSafe(e), chatSafe(f), chatSafe(g)))
    end
    for i = 1, 3 do
      local memberOk, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15 =
        pcall(C_LFGList.GetApplicantMemberInfo, id, i)
      if not memberOk then
        print(string.format("    member %d: call failed: %s", i, chatSafe(m2)))
      elseif m2 == nil then
        print(string.format("    member %d: nil", i))
      elseif type(m2) == "table" then
        print(string.format("    member %d: info table:", i))
        dumpTable("        ", m2)
      elseif true then
        print(string.format("    member %d: %s %s %s %s %s %s %s %s %s %s %s %s %s %s", i,
          chatSafe(m2), chatSafe(m3), chatSafe(m4), chatSafe(m5), chatSafe(m6), chatSafe(m7),
          chatSafe(m8), chatSafe(m9), chatSafe(m10), chatSafe(m11), chatSafe(m12), chatSafe(m13),
          chatSafe(m14), chatSafe(m15)))
      end
      -- Where the Mythic+ rating actually lives on this client: the positional dungeonScore reads 0
      -- for everyone, so print whatever the stats API exposes for the same member.
      if C_LFGList.GetApplicantMemberStats then
        local statsOk, stats = pcall(C_LFGList.GetApplicantMemberStats, id, i)
        if statsOk and type(stats) == "table" then
          local n = 0
          for _ in pairs(stats) do n = n + 1 end
          if n > 0 then
            print(string.format("      stats(%d):", i))
            dumpTable("        ", stats)
          end
        elseif statsOk and stats ~= nil then
          print(string.format("      stats(%d) = %s", i, chatSafe(stats)))
        end
      end
    end
  end
  local text = Roster.BuildText and Roster.BuildText() or ""
  print("bmpl dump: roster text the strip carries —")
  for line in tostring(text):gmatch("[^\n]+") do print("  " .. chatSafe(line)) end
end

SLASH_BMPL1 = "/bmpl"
SlashCmdList.BMPL = function(msg)
  msg = (msg or ""):lower():match("^%s*(.-)%s*$")
  if msg == "show" then
    forcedOn = true
    Strip.Rescale()
    print("bmpl: strip forced on — /bmpl hide to release it")
  elseif msg == "hide" then
    forcedOn = false
    print("bmpl: back to automatic (Group Finder open, or an active posting)")
  elseif msg == "selftest" then
    selftest()
  elseif msg == "dump" then
    dump()
  elseif msg:match("^cell%s") or msg == "cell" then
    local applied = Strip.SetCell(msg:match("^cell%s+(%d+)$"))
    if applied then
      print(string.format("bmpl: cell size %d px (strip is %dx%d px) — /reload restores the default",
        applied, 40 * applied, 16 * applied))
    else
      print(string.format("bmpl: /bmpl cell <3-10> — currently %d px", Strip.Cell()))
    end
  else
    print("bmpl: /bmpl show | hide | selftest | dump | cell <3-10>")
  end
end
