// Dev-only: regenerates addon/bmpl/tests/vectors.txt from today's codec (web/src/lib/live/codec.ts).
// Never imported by the test suite (test/live-vectors.test.ts only reads the committed file) and never
// spends WCL points — it is pure, offline codec math.
//
// Run after any change to codec.ts, chunkRoster's framing or the roster line format:
//   bun scripts/live-vectors.ts > addon/bmpl/tests/vectors.txt
//   bun test test/live-vectors.test.ts
//
// The Lua addon cannot read this file at runtime (no filesystem access in the WoW addon sandbox), so
// `/bmpl selftest` in main.lua carries its own copy of these same three vectors as Lua literals — keep
// that table in sync by hand when this file's rosters change. `test/live-vectors.test.ts` reads
// main.lua and fails if the two ever diverge, so "by hand" is checked, not trusted.
//
// Record format (tab-separated, one per line; `#` lines are comments):
//   frame <TAB> roster text (\n escaped) <TAB> rosterSeq <TAB> frame hex ... (one column per chunk)
//   cells <TAB> rosterSeq <TAB> chunkIndex <TAB> the 16x10 cell matrix, 160 bits MSB-first as 40 hex
// The `cells` records pin the *layout* (marker row, marker column, row-major MSB-first bits) that the
// frame bytes alone do not: `Encode.encodeCells` in the addon is otherwise checked by nothing.
import { bitsToBytes, chunkRoster, encodeCells, encodeFrame } from "../web/src/lib/live/codec.ts";

const hex = (b: Uint8Array) => [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
/** The 160-cell matrix packed MSB-first into 20 bytes — the same bit order the strip itself uses. */
const cellsHex = (cells: Uint8Array) => hex(bitsToBytes(cells));

type Role = "T" | "H" | "D";

// classIndex: src/wow/classes.ts (1 Death Knight, 4 Mage, 7 Priest, 8 Rogue, 11 Warrior). The line no
// longer carries a class name or a spec — v2 drops spec entirely (the panel never read it) and the
// class field is the addon's 1-byte class index, not the WCL name.
const line = (kind: "a" | "p" | "s", name: string, realm: string, classIndex: number, role: Role, score: number) =>
  `${kind}|${name}-${realm}|${classIndex}|${role}|${score}`;

const vectors: Array<{ text: string; seq: number }> = [
  // One applicant: the common case, one frame.
  {
    text: `${line("a", "Applicantone", "Area52", 1, "T", 1520)}\n`, // Death Knight
    seq: 1,
  },
  // Three applicants (oldest first) plus one party member — still one frame.
  {
    text: [
      line("a", "Applicanttwo", "Area52", 7, "H", 1480), // Priest
      line("a", "Applicantthree", "Stormrage", 4, "D", 1610), // Mage
      line("a", "Applicantfour", "Illidan", 8, "D", 0), // Rogue
      line("p", "Partymember", "Area52", 11, "T", 1550), // Warrior
    ].join("\n") + "\n",
    seq: 2,
  },
  // Twenty applicants: exercises chunkRoster's multi-frame split (well past the 18-byte payload cap),
  // and rosterSeq at its wire maximum (one byte, wraps at 256).
  {
    text:
      Array.from({ length: 20 }, (_, i) => {
        const n = i + 1;
        const role: Role = i % 3 === 0 ? "T" : i % 3 === 1 ? "H" : "D";
        const classIndex = i % 2 === 0 ? 4 : 7; // Mage / Priest
        return line("a", `Applicant${String(n).padStart(2, "0")}`, "Area52", classIndex, role, 1000 + i * 10);
      }).join("\n") + "\n",
    seq: 255,
  },
];

const lines = vectors.flatMap(({ text, seq }) => {
  const frames = chunkRoster(text, seq);
  return [
    ["frame", text.replaceAll("\n", "\\n"), String(seq), ...frames.map((f) => hex(encodeFrame(f)))].join("\t"),
    // One matrix per vector: the first chunk is enough to pin the layout, and keeping it to one keeps
    // main.lua's hand-copied mirror small.
    ["cells", String(seq), "0", cellsHex(encodeCells(frames[0]!))].join("\t"),
  ];
});

console.log([
  "# Golden vectors for addon/bmpl/encode.lua — generated by scripts/live-vectors.ts from web/src/lib/live/codec.ts.",
  "# frame <TAB> roster text (\\n escaped) <TAB> rosterSeq <TAB> one hex column per chunk",
  "# cells <TAB> rosterSeq <TAB> chunkIndex <TAB> the 16x10 matrix, 160 bits MSB-first as 40 hex chars",
  ...lines,
].join("\n"));
